spring:
 application:
   name: ShubhVivah
 datasource:
   username: root
   password: root
   driver-class-name: "com.mysql.jdbc.Driver"
   url: "jdbc:mysql://localhost/test"
 server:
   port: 8080
custom:
 property1: value1
 property2: value2